name: Build APK and release

on: 
  push:
    branches:
      - test
      - feature/github-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Fetch all files
      - uses: actions/checkout@v2

      # Setup .env file
      - run: touch .env
      - run: echo "API_URL='${{ secrets.API_URL }}'" >> .env
      - run: echo "GOOGLE_MAPS_API_KEY='${{ secrets.GOOGLE_MAPS_API_KEY }}'" >> .env 
      - run: echo "APP_IDENTIFIER='${{ secrets.APP_IDENTIFIER }}'" >> .env
      - run: echo "APP_HOST='${{ secrets.APP_HOST }}'" >> .env

      # Install flutter
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.5'
      - run: flutter pub get
      - run: flutter build apk

      # Release to Github
      - uses: ncipollo/release-action@v1
        with:
          tag: "latest"
          artifacts: "build/app/outputs/flutter-apk/app.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
